# Generated by Django 5.2.4 on 2025-08-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.ImageField(default='default.jpg', upload_to='blog_images/'),
        ),
    ]
