# Generated by Django 5.2.4 on 2025-08-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.ImageField(blank=True, default='blog_images/default.jpg', null=True, upload_to='blog_images/'),
        ),
    ]
