# Generated by Django 5.2.4 on 2025-08-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_registrationform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationForm',
            new_name='Registration',
        ),
    ]
