# Generated by Django 5.2.4 on 2025-08-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_registrationform_registration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
