# Generated by Django 5.2.4 on 2025-09-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='blog_images/user (1).png', null=True, upload_to='profile_pics/'),
        ),
    ]
